temp_login = 'appcoworking/login.html'
temp_login1 = 'login.html'
temp_registration = 'appcoworking/registration.html'
temp_main = 'main.html'
temp_all_users = 'all_users.html'
temp_details = 'details.html'
temp_template = 'template.html'
temp_users = 'users.html'