# Generated by Django 4.2.7 on 2024-07-03 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_product_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Заказ аренды', 'verbose_name_plural': 'Заказы аренды'},
        ),
        migrations.AddField(
            model_name='cartitem',
            name='order_day',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='order_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
