# Generated by Django 4.2.7 on 2024-07-23 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cartitem_end_date_cartitem_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='end_date',
            new_name='order_day',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='start_date',
            new_name='order_time',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='end_date',
            new_name='order_day',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='start_date',
            new_name='order_time',
        ),
    ]
