# Generated by Django 4.2.7 on 2024-07-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='computer',
            name='start_date',
            field=models.DateField(),
        ),
    ]
